name: socks5proxy

services:
  compiler:
    container_name: compiler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    working_dir: /root
    entrypoint: ["scripts/compile.sh"]
    env_file:
      - path: .env
        required: false

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
      - ${MOCK_ETC_HOST:-/dev/null}:/etc/hosts:ro
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/kernel/tracing:/sys/kernel/tracing
    privileged: "${TRACE:-false}"
    working_dir: /root
    entrypoint: ["scripts/server.sh"]
    ports:
      - "1080:1080"
      - "4242:4242"
    dns:
      - 8.8.8.8
    healthcheck:
      test: ["CMD-SHELL", "printf '\\005\\001\\002' | nc 127.0.0.1 1080 | head -c1 | grep -q \"$(printf '\\005')\""]
      start_period: 1s
      interval: 60s
      retries: 3
    networks:
      test-server-network:
        ipv4_address: 10.0.0.9
        ipv6_address: "fc00:00fe:0000:0000:0000:0000:0000:00fb"
    depends_on:
      compiler:
        condition: service_completed_successfully
    env_file:
      - path: .env
        required: false

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    working_dir: /root
    entrypoint: ["scripts/client.sh"]
    networks:
      test-server-network:
        ipv4_address: "10.0.0.5"
        ipv6_address: "fc00:00fe:0000:0000:0000:0000:0000:c1e0"
    depends_on:
      server:
        condition: service_healthy
      nginx-test-server:
        condition: service_healthy

  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    working_dir: /root
    entrypoint: ["scripts/tests.sh"]

  nginx-test-server:
    container_name: nginx-test-server
    networks:
      test-server-network:
        ipv4_address: "10.0.0.111"
        ipv6_address: "fc00:00fe:0000:0000:0000:0000:0000:00fe"
    image: nginx:latest
    volumes:
      - ./bench/data/www:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  benchmark:
    container_name: benchmark
    networks:
      test-server-network:
        ipv4_address: "10.0.0.99"
        ipv6_address: "fc00:00fe:0000:0000:0000:0000:0000:0099"
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    volumes:
      - .:/root
    working_dir: /root
    entrypoint: ["scripts/benchmark.sh"]
    depends_on:
      compiler:
        condition: service_completed_successfully
      server:
        condition: service_healthy
      nginx-test-server:
        condition: service_healthy

  show-results:
    container_name: bench-results
    image: nginx:latest
    volumes:
      - ./bench/results/jmeter-html-report:/usr/share/nginx/html:ro
    ports:
      - "8000:80"
    networks:
      - host-network
    depends_on:
      benchmark:
        condition: service_completed_successfully

networks:
  test-server-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fc00:00fe:0000::/64
          gateway: fc00:00fe:0000::1
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
  host-network:
    driver: bridge
